language: go

go:
  - 1.15.x
  - 1.16.x
  - 1.17.x

# Note: If you're working inside $GOPATH/src, go modules are disabled by default and can be enabled by setting GO111MODULE=on.
env:
  GO111MODULE=on

# 安装依赖
install:
  - go mod download

# 用来指定构建或测试脚本
script:
  - go test -v ./...
  - GOOS=windows GOARCH=amd64 go build -o music-get.exe
  - GOOS=linux GOARCH=amd64 go build -o music-get

before_deploy:
  - zip music-get_windows_amd64.zip music-get.exe README.md
  - zip music-get_linux_amd64.zip music-get README.md

deploy:
  provider: releases
  api_key: $API_KEY
  file:
    - music-get_windows_amd64.zip
    - music-get_linux_amd64.zip
  skip_cleanup: true
  on:
    tags: true
